### ISSUE TITLE
Build error on Arch Linux, Kernel 6.4.2

### ISSUE THREAD

**Issue by Brueggus** [fmorgner/dev-cyber#8]
I get the following errors on Arch Linux with Kernel 6.4.2:
[make.log](https://github.com/fmorgner/dev-cyber/files/12003338/make.log)

I have no clue about kernel development... if you need any additional information, please let me know.

**Comment by fmorgner** [comment]
Thanks for pointing this out! The issue was rooted in a change in Linux 6.4.0, which made the kernel more const-correct. Additionally, the `owner` field of the `class` structure was removed.

Fixed-by: 02519e2
